name: dart_telegram_avalon
description: Telegram bot 
version: 1.0.0

environment:
  sdk: ^3.0.2

dependencies:
  teledart: ^0.5.6
  firebase_dart: ^1.0.11

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
